// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBu-fn8uBpnUz5qk4a20VX7TgCTeVPea6s',
    appId: '1:638086617557:web:b805e9793f7d9e778b055c',
    messagingSenderId: '638086617557',
    projectId: 'chadchat-bb2db',
    authDomain: 'chadchat-bb2db.firebaseapp.com',
    storageBucket: 'chadchat-bb2db.appspot.com',
    measurementId: 'G-YZCH1THXDT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxUocFfEy_ys3pcb9Geniwl-tmkUfRmQA',
    appId: '1:638086617557:android:528410a16635a8f88b055c',
    messagingSenderId: '638086617557',
    projectId: 'chadchat-bb2db',
    storageBucket: 'chadchat-bb2db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_xZUcP6S5SbQJD_Ejio1PdMr6nOpVwwU',
    appId: '1:638086617557:ios:254b11e80ec979998b055c',
    messagingSenderId: '638086617557',
    projectId: 'chadchat-bb2db',
    storageBucket: 'chadchat-bb2db.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_xZUcP6S5SbQJD_Ejio1PdMr6nOpVwwU',
    appId: '1:638086617557:ios:bd2db2d20e2c84888b055c',
    messagingSenderId: '638086617557',
    projectId: 'chadchat-bb2db',
    storageBucket: 'chadchat-bb2db.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBu-fn8uBpnUz5qk4a20VX7TgCTeVPea6s',
    appId: '1:638086617557:android:528410a16635a8f88b055c',
    messagingSenderId: '638086617557',
    projectId: 'chadchat-bb2db',
    storageBucket: 'chadchat-bb2db.appspot.com',
  );
}
